contact_links:
  - name: Usage question & discussion
    url: https://github.com/Marcono1234/hda-fbi-typst-thesis-template/discussions
    about: Ask usage questions and discuss the thesis template in GitHub Discussions.
